### ISSUE TITLE
Problems with getting speaking URLs

### ISSUE THREAD

**Issue by criwe** [featdd/dpn_glossary#152]
Hi!
I´ve using the newest version of dpn glossary in an TPYO3 9 (updated from 8). Now I´m trying to get speaking urls.

This is my config.yaml of the site:

```
base: 'https://my.domain.de'
baseVariants: {  }
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
    languageId: '0'
rootPageId: 2
routes: {  }
routeEnhancers:
  DpnGlossary:
    type: Extbase
    limitToPages: [1117]
    extension: DpnGlossary
    plugin: glossary
    routes:
    - { routePath: '/{character}', _controller: 'Term::list', _arguments: {'character': '@widget_0/character'} }
    - { routePath: '/{localized_term}/{term_name}', _controller: 'Term::show', _arguments: {'term_name': 'term'} }
    defaultController: 'Term::list'
    defaults:
      character: ''
    aspects:
      term_name:
        type: PersistedAliasMapper
        tableName: 'tx_dpnglossary_domain_model_term'
        routeFieldName: 'url_segment'
      character:
        type: StaticMultiRangeMapper
        ranges:
          - start: 'A'
            end: 'Z'
      localized_term:
        type: LocaleModifier
        default: 'term'
        localeMap:
        - locale: 'de_DE.*'
          value: 'begriff'
  PageTypeSuffix:
    type: PageType
    default: /
    suffix: /
    index: ''
    map:
      /: 0
```
Structure:

page 1117 -> Plugin (Listview)
   Subpage (folder with terms)

Wenn calling page 1117, if got an "Oops, an error occurred! Code...." where the plugin should be. When removing the config, it works fine (but no speaking URLs).

I´ve tried a fews thing, but don´t get it running. Any ideas?
Thanks!
Best
Christoph
