### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by hempelta** [featdd/dpn_glossary#159]
Hello,

i have a problem with url_segment of terms. In the backend it only shows "https://project.ddev.site:443" but not "https://project.ddev.site:443/glossar/begriff". The term is parsed in the frontend, but the link only points to "https://project.ddev.site:443#myTerm". 

Can you help me?

my config

pid 67 insert plugin dpnglossary_glossary with stroage pid 67 and recursive = 0

```
plugin.tx_dpnglossary {
    persistence {
        storagePid = 67
    }
    settings {
        addStylesheet = 0
        detailPage = 67
        previewmode = pagination
        pagination {
            characters = A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z
            insertAbove = 1
            insertBelow = 1
        }
    }
}
```

```
TCEFORM {
    tx_dpnglossary_domain_model_term {
        url_segment.config.previewUrl.pageUid = 67
    }
}
```

```
routeEnhancers:
  DpnGlossary:
    type: Extbase
    limitToPages: 67
    extension: DpnGlossary
    plugin: glossary
    routes:
      - { routePath: '/{character}', _controller: 'Term::list', _arguments: { 'character': '@widget_0/character' } }
      - { routePath: '/{localized_term}/{term_name}', _controller: 'Term::show', _arguments: { 'term_name': 'term' } }
    defaultController: 'Term::list'
    defaults:
      character: ''
    aspects:
      term_name:
        type: PersistedAliasMapper
        tableName: 'tx_dpnglossary_domain_model_term'
        routeFieldName: 'url_segment'
      character:
        type: StaticMultiRangeMapper
        ranges:
          - start: 'A'
            end: 'Z'
      localized_term:
        type: LocaleModifier
        default: 'term'
        localeMap:
          - locale: 'de_DE.*'
            value: 'begriff'
```
