### ISSUE TITLE
Problems with getting speaking URLs

### ISSUE THREAD

**Issue by martinschoene** [featdd/dpn_glossary#160]
hi,
after adding these lines to my siteconfig:
```
PageTypeSuffix:   
    type: PageType
    default: /
    index: ''
    map:
      /: 0
```
i am getting the following error:

`Oops, an error occurred! Code: 202012151248435f9e6a74 - {"exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException: Parameter \"t3be3391e96edf93e3ad4c195a24a51\" for route \"tx_dpnglossary_glossary_0\" must match \".+\" (\"\" given) to generate a corresponding URL......`

before adding the PageTypeSuffix, it works perfectly

TYPO3 10.4.10
dpn_glossary 3.1.6

greetings martin

**Comment by featdd** [comment]
Hi @martinschoene,

could you try this:

```
PageTypes:
  type: PageType
  default: /
  index: ''
  map:
    /: 0
```

Greetings
Daniel
