### ISSUE TITLE
Multi-byte characters not supported by pagination

### ISSUE THREAD

**Issue by cortexmediaulm** [featdd/dpn_glossary#161]
When using non-latin characters for pagination, for example cyrillic characters, the pagination will be empty. 

For example when setting this:
```
plugin.tx_dpnglossary.settings.pagination.characters = А,Б,В,Г,Д,Е,Ж,З,И,Й,К,Л,М,Н,О,П,Р,С,Т,У,Ф,Х,Ц,Ч,Ш,Щ,Ъ,Ь,Ю,Я
```
the pagination will render empty letters because no terms can be found within `PaginationController->getMatchings()`.

The root cause is the `str_split` function used here: https://github.com/featdd/dpn_glossary/blob/72c9c95c469d959b2eda3b63168a0d0edada6ee3/Classes/ViewHelpers/Widget/Controller/PaginateController.php#L239

This assumes that the characters are represented as 1-byte chars, but this is not the case for cyrillic (or other non-ascii or non-latin) characters. 

Possible solution: `explode()` instead of `str_split()`:
```
$charactersArray = explode(',', $characters);
```

**Comment by featdd** [comment]
Hi @cortexmediaulm,

thanks for the issue and the possible solution, I don't have much experience with this case so I'll have to try this out.

Greetings
Daniel

**Comment by featdd** [comment]
Hi @cortexmediaulm,

I solved the issue, I just had to use the multibyte functions. See: ccba08bac08fa0e81cef3411b0d85f33a3436e1b

But there was another issue following onto, the pagination range builder doesn't seem to work for cyrillic characters, do you also have an idea for this?

Currently this is used and works fine for latin characters:

`$range = array_map('\strval', range($start, $end));`

As a workaround I used the StaticValueMapper feature like this:

```
character:
  type: StaticValueMapper
  map:
    A: 'А'
    B: 'Б'
    C: 'В'
    D: 'Г'
    E: 'Д'
    F: 'Е'
    G: 'Ж'
    H: 'З'
    I: 'И'
    J: 'Й'
    K: 'К'
    L: 'Л'
    M: 'М'
    N: 'Н'
    O: 'О'
    P: 'П'
    Q: 'Р'
    R: 'С'
    S: 'Т'
    T: 'У'
    U: 'Ф'
    V: 'Х'
    W: 'Ц'
    X: 'Ч'
    Y: 'Ш'
    Z: 'Щ'
```

**Comment by cortexmediaulm** [comment]
Thanks for the effort! We are scheduling an update of the extension in the next days.

**Comment by featdd** [comment]
Hi @cortexmediaulm,

I just pushed a new release (v3.2.2) to TER.

I couldn't solve the issue for the range builder, but you can still use the mapper like here: https://github.com/featdd/dpn_glossary/issues/161#issuecomment-826385982

Greetings
Daniel

**Comment by cortexmediaulm** [comment]
Hi @featdd 

where did you place the `StaticValueMapper` part? In the global `config.yaml` site configuration file? Or anywhere else?

> But there was another issue following onto, the pagination range builder doesn't seem to work for cyrillic characters, do you also have an idea for this?
> 
> Currently this is used and works fine for latin characters:
> 
> `$range = array_map('\strval', range($start, $end));`
> 
> As a workaround I used the StaticValueMapper feature like this:
> 
> ```
> character:
>   type: StaticValueMapper
>   map:
>     A: 'А'
>     B: 'Б'
>     C: 'В'
>     D: 'Г'
>     E: 'Д'
>     F: 'Е'
>     G: 'Ж'
>     H: 'З'
>     I: 'И'
>     J: 'Й'
>     K: 'К'
>     L: 'Л'
>     M: 'М'
>     N: 'Н'
>     O: 'О'
>     P: 'П'
>     Q: 'Р'
>     R: 'С'
>     S: 'Т'
>     T: 'У'
>     U: 'Ф'
>     V: 'Х'
>     W: 'Ц'
>     X: 'Ч'
>     Y: 'Ш'
>     Z: 'Щ'
> ```

**Comment by featdd** [comment]
Hi @cortexmediaulm,

you have to put it in your routeEnhancer configuration, like in this example:

```
routeEnhancers:
  DpnGlossary:
    type: Extbase
    limitToPages:
      - 4
    extension: DpnGlossary
    plugin: glossary
    routes:
      - routePath: '/{character}'
        _controller: 'Term::list'
        _arguments:
          character: '@widget_0/character'
      - routePath: '/{localized_term}/{term_name}'
        _controller: 'Term::show'
        _arguments:
          term_name: term
    defaultController: 'Term::list'
    defaults:
      character: ''
    aspects:
      term_name:
        type: PersistedAliasMapper
        tableName: tx_dpnglossary_domain_model_term
        routeFieldName: url_segment
      character:
        type: StaticValueMapper
        map:
          A: 'А'
          B: 'Б'
          C: 'В'
          D: 'Г'
          E: 'Д'
          F: 'Е'
          G: 'Ж'
          H: 'З'
          I: 'И'
          J: 'Й'
          K: 'К'
          L: 'Л'
          M: 'М'
          N: 'Н'
          O: 'О'
          P: 'П'
          Q: 'Р'
          R: 'С'
          S: 'Т'
          T: 'У'
          U: 'Ф'
          V: 'Х'
          W: 'Ц'
          X: 'Ч'
          Y: 'Ш'
          Z: 'Щ'
      localized_term:
        type: LocaleModifier
        default: term
        localeMap:
          - locale: 'de_DE.*'
            value: begriff
```

For further information have a look into the [official documentation](https://docs.typo3.org/m/typo3/reference-coreapi/10.4/en-us/ApiOverview/Routing/AdvancedRoutingConfiguration.html)

Greetings
Daniel
