### ISSUE TITLE
URL configuration

### ISSUE THREAD

**Issue by danaron** [featdd/dpn_glossary#175]
Hi,
I did try to make human readable URLs, but did not succed.

In the page configuration file config.yaml i do have this code:

```
DpnGlossary:
  type: Extbase
  limitToPages: 88
  extension: DpnGlossary
  plugin: glossary
  routes:
  - { routePath: '/{character}', _controller: 'Term::list', _arguments: {'character': '@widget_0/character'} }
  - { routePath: '/{localized_term}/{term_name}', _controller: 'Term::show', _arguments: {'term_name': 'term'} }
  defaultController: 'Term::list'
  defaults:
    character: ''
  aspects:
    term_name:
      type: PersistedAliasMapper
      tableName: 'tx_dpnglossary_domain_model_term'
      routeFieldName: 'url_segment'
    character:
      type: StaticMultiRangeMapper
      ranges:
        - start: 'A'
          end: 'Z'
    localized_term:
      type: LocaleModifier
      default: 'term'
      localeMap:
      - locale: 'de_CH.*'
        value: 'begriff'
```
And in the page-TSconfig, where the Plugin for detail view is i did write:

```
TCEFORM {
  tx_dpnglossary_domain_model_term {
    url_segment.config.previewUrl.pageUid = 88
  }
}
```

Any ideas, why this is not working?
Thank you for your help and the great plugin!
Best regards
Dan

**Comment by featdd** [comment]
Hi @danaron,

it seems you're using an older configuration still using the widget param for the character.
Please have a look into the documentation, you can find the latest [example](https://docs.typo3.org/p/featdd/dpn-glossary/4.1/en-us/Configuration/ExampleTypoScriptSetup/Index.html#configure-routing-for-terms-and-pagination) here.

Greetings
Daniel

**Comment by danaron** [comment]
Hi Daniel,
Thank  you for your quick answer.
When I do follow the link you mentioned, it is ecactly the same configuration, or I am wrong?

```
DpnGlossary:
  type: Extbase
  limitToPages: [YOUR_PLUGINPAGE_UID]
  extension: DpnGlossary
  plugin: glossary
  routes:
  - { routePath: '/{character}', _controller: 'Term::list', _arguments: {'character': 'currentCharacter'} }
  - { routePath: '/{localized_term}/{term_name}', _controller: 'Term::show', _arguments: {'term_name': 'term'} }
  defaultController: 'Term::list'
  defaults:
    character: ''
  aspects:
    term_name:
      type: PersistedAliasMapper
      tableName: 'tx_dpnglossary_domain_model_term'
      routeFieldName: 'url_segment'
    character:
      type: StaticMultiRangeMapper
      ranges:
        - start: 'A'
          end: 'Z'
    localized_term:
      type: LocaleModifier
      default: 'term'
      localeMap:
      - locale: 'de_DE.*'
        value: 'begriff'
```
Thanks for clarification.
Have a nice weekend
Dan

**Comment by danaron** [comment]
To all that are curious. It was not working because of the missing "routeEnhancers:" in the first line.
This is how it works now:
```
routeEnhancers:
  DpnGlossary:
    type: Extbase
    limitToPages: 88
    extension: DpnGlossary
    plugin: glossary
    routes:
      - routePath: '/{character}'
        _controller: 'Term::list'
        _arguments:
          character: currentCharacter
      - routePath: '/{term_name}'
        _controller: 'Term::show'
        _arguments:
          term_name: term
    defaultController: 'Term::list'
    defaults:
      character: ''
    aspects:
      term_name:
        type: PersistedAliasMapper
        tableName: tx_dpnglossary_domain_model_term
        routeFieldName: url_segment
      character:
        type: StaticMultiRangeMapper
        ranges:
          - start: A
            end: Z
      localized_term:
        type: LocaleModifier
        default: 'term'
        localeMap:
          - locale: 'de_CH.*'
            value: 'begriff'
```
